name: CI

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  node18:
    name: Node 18
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
  node20:
    name: Node 20
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
  node22:
    name: Node 22
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run lint
      - run: npm run cs
      - name: sonarcloud.io
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
